[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Language = ["en"] }

#[context.production.environment]
#  NETLIFY_DATABASE_URL = "your_database_url_here"
